apiVersion: v1
kind: Service
metadata:
  name: staging-mirage-multicfg-01
  namespace: cs2-servers
  labels:
    app.kubernetes.io/name: cs2-server
    zizo.gg/server-id: staging-mirage-multicfg-01
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: cs2-server
    zizo.gg/server-id: staging-mirage-multicfg-01
  ports:
    - name: game-tcp
      port: 26001
      targetPort: game-tcp
      protocol: TCP
    - name: game-udp
      port: 26001
      targetPort: game-udp
      protocol: UDP
