apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staging-mirage-multicfg-01-data
  namespace: cs2-servers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 120Gi
