name: all-weapons-dm
displayName: All Weapons DM
defaultMap: de_mirage
exec: all-weapons-dm.cfg
maxPlayers: 24
gameType: 1
gameMode: 2
mapGroup: mg_dm
plugins:
  enabled:
    - cs2rcon
  disabledRuntime:
    - CS2-SimpleAdmin
    - CS2-CustomVotes
    - GameModeManager
    - MenuManagerAPI
    - MenuManagerCore
    - PlayerSettings
